---

- name: Check if CA certificate exists
  stat:
    path: "{{ taskd_ca_cert }}"
  register: _result

- name: Get CA certificate info
  openssl_certificate_info:
    path: "{{ taskd_ca_cert }}"
    valid_at:
      now: "+0s"
  register: _result
  when: _result.stat.exists | bool

- name: Generate certificates
  # when: _result is failed or _result is skipped or not _result.valid_at.now | bool
  block:
    - name: Copy selfsigning vars file to location
      template:
        src: ssl_vars.j2
        dest: "{{ taskd_install_location }}/pki/vars"
        owner: "{{ taskd_user }}"
        group: "{{ taskd_group }}"

    # TODO allow renewing certs
    - name: Run generate cert script
      shell: ./generate
      args:
        chdir: "{{ taskd_install_location }}/pki/"

    - name: Copy generated certs to data location
      copy:
        src: "{{ taskd_install_location }}/pki/{{ item.0 }}"
        dest: "{{ lookup('vars', item.1) }}"
        owner: "{{ taskd_user }}"
        group: "{{ taskd_group }}"
        remote_src: true
      loop: "{{ list1 | zip(list2) | list }}"
      vars:
        list1:
          - server.cert.pem
          - server.key.pem
          - server.crl.pem
          - client.cert.pem
          - client.key.pem
          - ca.cert.pem
          - ca.key.pem
        list2:
          - taskd_server_cert
          - taskd_server_key
          - taskd_server_crl
          - taskd_client_cert
          - taskd_client_key
          - taskd_ca_cert
          - taskd_ca_key
      notify: taskd restart service

    - name: Run generate client cert script
      shell: "./generate.client {{ item.name|replace(' ', '_') }}"
      args:
        chdir: "{{ taskd_install_location }}/pki/"
      register: result
      loop: "{{ taskd_users }}"

    - name: Create user certs folder
      file:
        path: "{{ taskd_user_cert_location }}"
        owner: "{{ taskd_user }}"
        group: "{{ taskd_group }}"
        mode: 0o755
        state: directory

    - name: Move generated user certs
      command: >-
        mv
          {{ taskd_install_location }}/pki/{{ item.name|replace(' ', '_')
            }}.cert.pem
          {{ taskd_install_location }}/pki/{{ item.name|replace(' ', '_')
            }}.key.pem
          {{ taskd_user_cert_location }}/
      when: result.results[index] is changed
      loop: "{{ taskd_users }}"
      loop_control:
        index_var: index
