---

- name: Restart taskd service
  service:
    name: taskd
    enabled: true
    daemon_reload: true
    state: restarted
  listen: taskd restart service

- name: Restart taskwarrior-sync timer
  service:
    name: taskwarrior-sync.timer
    enabled: true
    daemon_reload: true
    state: restarted
  listen: taskd restart sync timer
